# Generated by Django 3.2.4 on 2021-06-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0006_auto_20200327_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktor',
            name='filmy',
            field=models.ManyToManyField(related_name='aktorzy', to='filmyweb.Film'),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Komedia'), (1, 'Horror'), (4, 'Drama'), (3, 'Sci-fi')], default=0),
        ),
    ]
