# Generated by Django 3.2.4 on 2021-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0007_auto_20210628_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (1, 'Horror'), (2, 'Komedia'), (0, 'Inne'), (4, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='opis',
            field=models.TextField(default='', max_length=30),
        ),
    ]
