# Generated by Django 3.2.4 on 2021-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0008_auto_20210708_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (5, 'Przygodowy'), (4, 'Drama'), (0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (5, 'Akcja')], default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='opis',
            field=models.TextField(default='', max_length=230),
        ),
    ]
