# Generated by Django 3.2.4 on 2021-07-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0009_auto_20210712_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (5, 'Przygodowy'), (5, 'Akcja'), (3, 'Sci-fi'), (2, 'Komedia'), (4, 'Drama')], default=0),
        ),
    ]
