# Generated by Django 3.2.4 on 2021-07-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0012_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (0, 'Inne'), (5, 'Przygodowy'), (5, 'Akcja'), (1, 'Horror'), (4, 'Drama'), (3, 'Sci-fi')], default=0),
        ),
    ]
