# Generated by Django 3.2.4 on 2021-07-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0014_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (2, 'Komedia'), (5, 'Przygodowy'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror'), (5, 'Akcja')], default=0),
        ),
    ]
