# Generated by Django 3.2.4 on 2021-07-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0016_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rezyseria',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (0, 'Inne'), (5, 'Akcja'), (1, 'Horror'), (3, 'Sci-fi'), (5, 'Przygodowy'), (2, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='opis',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
