# Generated by Django 3.2.4 on 2021-07-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0017_auto_20210722_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='produkcja',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='scenaruisz',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Komedia'), (5, 'Przygodowy'), (3, 'Sci-fi'), (1, 'Horror'), (5, 'Akcja'), (4, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='rezyseria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
