# Generated by Django 3.2.4 on 2021-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0018_auto_20210722_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (3, 'Sci-fi'), (0, 'Inne'), (2, 'Komedia'), (5, 'Akcja'), (1, 'Horror'), (6, 'Przygodowy')], default=0),
        ),
    ]
