# Generated by Django 3.2.4 on 2021-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0019_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (6, 'Przygodowy'), (2, 'Komedia'), (5, 'Akcja'), (1, 'Horror'), (4, 'Drama')], default=0),
        ),
    ]
