# Generated by Django 3.2.4 on 2021-07-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0020_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='premiera',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Przygodowy'), (0, 'Inne'), (4, 'Drama'), (2, 'Komedia'), (3, 'Sci-fi'), (5, 'Akcja'), (1, 'Horror')], default=0),
        ),
    ]
