# Generated by Django 3.2.4 on 2021-07-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0021_auto_20210726_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='filmiki',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Akcja'), (0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (4, 'Drama'), (6, 'Przygodowy')], default=0),
        ),
    ]
