# Generated by Django 3.2.4 on 2021-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0023_auto_20210730_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='url',
            new_name='url_movie',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (4, 'Drama'), (6, 'Przygodowy'), (5, 'Akcja'), (1, 'Horror'), (0, 'Inne')], default=0),
        ),
    ]
