# Generated by Django 3.2.4 on 2021-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0025_auto_20210730_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (0, 'Inne'), (3, 'Sci-fi'), (5, 'Akcja'), (2, 'Komedia'), (6, 'Przygodowy'), (1, 'Horror')], default=0),
        ),
    ]
