# Generated by Django 3.2.4 on 2021-07-30 08:44

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0026_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='url_movie',
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (4, 'Drama'), (1, 'Horror'), (5, 'Akcja'), (2, 'Komedia'), (6, 'Przygodowy'), (0, 'Inne')], default=0),
        ),
    ]
