# Generated by Django 3.2.4 on 2021-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0028_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (3, 'Sci-fi'), (5, 'Akcja'), (2, 'Komedia'), (4, 'Drama'), (0, 'Inne'), (6, 'Przygodowy')], default=0),
        ),
    ]
