# Generated by Django 3.2.6 on 2021-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0030_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Inne'), (2, 'Komedia'), (1, 'Horror'), (5, 'Akcja'), (6, 'Przygodowy'), (4, 'Drama')], default=0),
        ),
    ]
