# Generated by Django 3.2.6 on 2021-08-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0031_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dystrybutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(5, 'Akcja'), (1, 'Horror'), (3, 'Sci-fi'), (4, 'Drama'), (2, 'Komedia'), (6, 'Przygodowy'), (0, 'Inne')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.dystrybutor'),
        ),
        migrations.DeleteModel(
            name='DodatkoweInfo',
        ),
    ]
