# Generated by Django 3.2.6 on 2021-08-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0034_alter_dystrybutor_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dystrybutor',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (5, 'Akcja'), (2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (6, 'Przygodowy'), (4, 'Drama')], default=0),
        ),
    ]
