# Generated by Django 3.2.6 on 2021-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0036_auto_20210815_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dystrybutor2',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (6, 'Przygodowy'), (1, 'Horror'), (5, 'Akcja'), (4, 'Drama'), (3, 'Sci-fi'), (0, 'Inne')], default=0),
        ),
    ]
