# Generated by Django 3.2.6 on 2021-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0038_alter_dystrybutor2_gatunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dystrybutor2',
            name='czas_trwania',
        ),
        migrations.AddField(
            model_name='film',
            name='czas_trwania',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dystrybutor2',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Akcja'), (2, 'Komedia'), (3, 'Sci-fi'), (6, 'Przygodowy'), (4, 'Drama'), (1, 'Horror'), (0, 'Inne')], default=0),
        ),
    ]
