# Generated by Django 3.2.6 on 2021-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0039_auto_20210815_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dystrybutor2',
            name='gatunek',
        ),
        migrations.AddField(
            model_name='dystrybutor2',
            name='dys_adres',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dystrybutor2',
            name='dys_nazwa',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dystrybutor2',
            name='dys_nip',
            field=models.TextField(default='', max_length=10),
        ),
    ]
