# Generated by Django 3.2.6 on 2021-08-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0040_auto_20210815_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.PositiveSmallIntegerField(default=0, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='dystrybutor2',
            name='dys_adres',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dystrybutor2',
            name='dys_nazwa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dystrybutor2',
            name='dys_nip',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='film',
            name='gatunek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.gatunek'),
        ),
    ]
