# Generated by Django 3.2.6 on 2021-08-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0041_auto_20210815_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gatunek',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.gatunek'),
        ),
    ]
