# Generated by Django 3.2.6 on 2021-08-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0043_alter_gatunek_gatunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatunek',
            name='gatunek',
        ),
        migrations.AddField(
            model_name='gatunek',
            name='gat_nazwa',
            field=models.CharField(default='', max_length=150),
        ),
    ]
