# Generated by Django 3.2.6 on 2021-08-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0044_auto_20210815_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatunek',
            old_name='gat_nazwa',
            new_name='gatunek',
        ),
    ]
