# Generated by Django 3.2.6 on 2021-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0049_alter_gatunek_gatunek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='tytul',
            new_name='film_tytul',
        ),
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek',
            field=models.CharField(default='', max_length=150),
        ),
    ]
