# Generated by Django 3.2.6 on 2021-08-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0051_alter_gatunek_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gatunek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.gatunek'),
        ),
    ]
