# Generated by Django 3.2.6 on 2021-08-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0052_alter_film_gatunek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='czas_trwania',
            new_name='film_czas_trwania',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='dodatkowe',
            new_name='film_dodatkowe',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='opis',
            new_name='film_opis',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='plakat',
            new_name='film_plakat',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='produkcja',
            new_name='film_produkcja',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='rezyseria',
            new_name='film_rezyseria',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='rok',
            new_name='film_rok',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='scenaruisz',
            new_name='film_scenaruisz',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='video',
            new_name='film_video',
        ),
        migrations.RemoveField(
            model_name='film',
            name='gatunek',
        ),
        migrations.RemoveField(
            model_name='film',
            name='imdb_rating',
        ),
        migrations.AddField(
            model_name='film',
            name='film_gatunek',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.gatunek'),
        ),
    ]
