# Generated by Django 3.2.6 on 2021-08-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0053_auto_20210815_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
