# Generated by Django 3.2.6 on 2021-08-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0058_alter_gatunek_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_gatunek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.gatunek'),
        ),
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
