# Generated by Django 3.2.6 on 2021-08-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0059_auto_20210816_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_gatunek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filmyweb.gatunek'),
        ),
    ]
