# Generated by Django 3.2.6 on 2021-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0061_alter_film_film_gatunek'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_identyfikator',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='film_kraj_produkcji',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='film_tytul_oryginalny',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Napisy', 'Napisy'), ('Oryginalna', 'Oryginalna'), ('Lektor', 'Lektor'), ('Dubbing', 'Dubbing')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='film_wersja_wyswietlania',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
