# Generated by Django 3.2.6 on 2021-08-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0062_auto_20210816_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Napisy', 'Napisy'), ('Oryginalna', 'Oryginalna'), ('Dubbing', 'Dubbing'), ('Lektor', 'Lektor')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_wyswietlania',
            field=models.CharField(choices=[('3D', '3D'), ('2D', '2D')], default='', max_length=12),
        ),
    ]
