# Generated by Django 3.2.6 on 2021-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0064_auto_20210816_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film_rok',
            new_name='film_rok_produkcji',
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Oryginalna', 'Oryginalna'), ('Napisy', 'Napisy'), ('Dubbing', 'Dubbing'), ('Lektor', 'Lektor')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_wyswietlania',
            field=models.CharField(choices=[('3D', '3D'), ('2D', '2D')], default='', max_length=12),
        ),
    ]
