# Generated by Django 3.2.6 on 2021-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0065_auto_20210816_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dystrybutor2',
            new_name='Dystrybutor',
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Oryginalna', 'Oryginalna'), ('Lektor', 'Lektor'), ('Dubbing', 'Dubbing'), ('Napisy', 'Napisy')], default='', max_length=12),
        ),
    ]
