# Generated by Django 3.2.6 on 2021-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0066_auto_20210816_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film_dodatkowe',
            new_name='dodatkowe',
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Oryginalna', 'Oryginalna'), ('Napisy', 'Napisy'), ('Lektor', 'Lektor'), ('Dubbing', 'Dubbing')], default='', max_length=12),
        ),
    ]
