# Generated by Django 3.2.6 on 2021-08-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0067_auto_20210816_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Dubbing', 'Dubbing'), ('Oryginalna', 'Oryginalna'), ('Lektor', 'Lektor'), ('Napisy', 'Napisy')], default='', max_length=12),
        ),
    ]
