# Generated by Django 3.2.6 on 2021-08-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0069_alter_film_film_wersja_jezykowa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Oryginalna', 'Oryginalna'), ('Lektor', 'Lektor'), ('Napisy', 'Napisy'), ('Dubbing', 'Dubbing')], default='', max_length=12),
        ),
    ]
