# Generated by Django 3.2.6 on 2021-08-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0072_auto_20210816_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kraj_produkcji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj_produkcji', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Dubbing', 'Dubbing'), ('Oryginalna', 'Oryginalna'), ('Napisy', 'Napisy'), ('Lektor', 'Lektor')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_kraj_produkcji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.kraj_produkcji'),
        ),
    ]
