# Generated by Django 3.2.6 on 2021-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0073_auto_20210816_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_kraj_produkcji',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Oryginalna', 'Oryginalna'), ('Napisy', 'Napisy'), ('Dubbing', 'Dubbing'), ('Lektor', 'Lektor')], default='', max_length=12),
        ),
        migrations.DeleteModel(
            name='Kraj_produkcji',
        ),
    ]
