# Generated by Django 3.2.6 on 2021-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0076_auto_20210816_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_wersja_jezykowa',
            field=models.CharField(choices=[('Lektor', 'Lektor'), ('Dubbing', 'Dubbing'), ('Napisy', 'Napisy'), ('Oryginalna', 'Oryginalna')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_wersja_wyswietlania',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='', max_length=12),
        ),
    ]
